branches:
  except:
    - travis
language: java
jdk:
- oraclejdk8
script:
- mvn test jacoco:report coveralls:report
notifications:
  slack: cloudfoundry:xvgjKLNQTyqAFMnsTywVHik9
after_success:
- mvn deploy --settings settings.xml
- mkdir -p /tmp/spring-content/docs
- mv paulcwarren/spring-content/spring-content-fs/target/generated-docs/*.html /tmp/spring-content-docs/refs/current/
- git config --global user.email GITHUB_EMAIL
- git config --global user.name GITHUB_NAME
- git checkout gh-pages
- mv /tmp/spring-content-docs/refs/current/*.html refs/current/
- git add refs/current/
- git commit --message "SpringContentCI: Publishing References"
- git remote add origin-pages GITHUB_LINK > /dev/null 2>&1
- git push --quiet --set-upstream origin-pages gh-pages
