branches:
  except:
    - travis
language: java
jdk:
- oraclejdk8
env:
- MAVEN_PROFILE=master
before_install:
- ./scripts/before-install.sh
deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true
#script:
#- mvn deploy --settings settings.xml -P $MAVEN_PROFILE jacoco:report coveralls:report 
notifications:
  slack: cloudfoundry:xvgjKLNQTyqAFMnsTywVHik9
after_success:
- mvn scm-publish:publish-scm
