branches:
  except:
    - travis
language: java
jdk:
- oraclejdk8
before_install:
- ./scripts/before-install.sh
script:
- mvn deploy --settings settings.xml -P $TRAVIS_BRANCH jacoco:report coveralls:report 
notifications:
  slack: cloudfoundry:xvgjKLNQTyqAFMnsTywVHik9
after_success:
- mvn scm-publish:publish-scm
