branches:
  except:
    - travis
language: java
jdk:
- oraclejdk8
script:
- mvn test jacoco:report coveralls:report
notifications:
  slack: cloudfoundry:xvgjKLNQTyqAFMnsTywVHik9
after_success:
- mvn deploy --settings settings.xml
- mkdir -p gh-pages
- cd gh-pages
- git config --global user.email GITHUB_EMAIL
- git config --global user.name GITHUB_NAME
- git checkout -b gh-pages
- mv spring-content/spring-content-fs/target/generated-docs/*.html ./refs/current/
- git add refs/current/
- git commit --message "SpringContentCI: Publishing References"
- git remote add origin-pages GITHUB_LINK > /dev/null 2>&1
- git push --quiet --set-upstream origin-pages gh-pages
